<font size="1"> *This notebook is best viewed in jupyter lab/notebook. You may also choose to use Google Colab but some parts of the images/colouring will not be rendered properly.</font> 

<div class="alert alert-block alert-warning">

# <p style="text-align: center;">Lab 1 (Weeks 1,2): Python Basics - Part 1 Basics Notebook</p>

<img src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" width="200" height="200" />

Welcome to your very first lab of ECE4179. Labs in this unit will run as a help desk and they are not mandatory to attend.   

The two notebooks provided contain all the code and comments that you need to submit. Feel free to add in your own markdown for additional comments.

Here are the instructions to complete this lab:

- The marks of the lab is based on the Moodle '**Lab 1 Quiz**' attempt.
- You need to submit both Jupyter Notebooks (.ipynb file) to Moodle submission box '**Lab 1 Submission**'.
- We do not directly mark your notebook, but it is required to show your work out for the questions.
- If the notebook is not submitted, we consider the lab is not completed and no marks will be given for the quiz questions.
- In some sections, we ask for screenshots of your code and plot. Please make sure to add your name and student ID to the title of the plot (which means it will also show in your code).
- You can directly copy and paste the screenshots into the text box, and add multiple ones if needed.
- We do not require you to complete every single section in the notebook. However, for the parts that we ask for a screenshot of your code and outputs, we require those parts to be completed. And the code completed should be functional, ie, if we asked for a screenshot for part 2.2, and the code is dependent on part 2.1, then both parts in the notebook should be completed.
        
In this Lab, you will find four tasks distributed across two notebooks: Basics and Applications. The first two tasks test your basic python knowledge and the applcations of numpy and matplotlib libraries. The last two tasks, you will apply the knowledge you gained so far to solve practical problems.
- <b>Task 1:</b> Python Basics
- <b>Task 2:</b> Data Analysis and Visualization
- <b>Task 3:</b> Wanna play Darts?
- <b>Task 4:</b> Thinking inside the ball!
      
Each task will contain code to complete, and a worded question, so ensure you complete both bfeore submitting.

Good luck with the Lab! Submit it before the deadline to enjoy full marks.

<b>Enter you student details below</b>

- <b>Student Name:</b> Lucas Liu
- <b>Student ID:</b> 31445179

<div class="alert alert-block alert-danger">

## Table of Contents

* [Libraries](#Libraries)


* [Task 1: Python basics](#python-basics)    
    * [1.1 Data types](#data-types) 
    * [1.2 Conditional statements](#conditional-statements)   
    * [1.3 Loops](#loops)    
    * [1.4 Functions](#functions)    
    * [1.5 Classes](#classes)
    
    
* [Task 2: Data Analysis and Visualization](#data-analysis-and-visualization)  
    * [2.1 Numpy](#numpy)
    * [2.2 Matplotlib](#matplotlib)

<div class="alert alert-block alert-warning">

# Libraries

Libraries are important as it saves us time from writing our own functions all the time such as graphing, or creating matrices. Brief library descriptions have been added for every library that we import. You may also check the official documentations for more details.

We can use the "import" function to import libraries, and use _as_ to rename the library within our workspace. For example, we could have used _import numpy_ by itself, and referenced Numpy functions by _numpy.function_, but instead we have an alias of Numpy as _np.function_ instead. 

In [ ]:
## Libraries, you do not need to import any additional libraries for this lab

import numpy as np  ## Numpy is the fundamental building block of understanding tensor (matrices) within Python
import matplotlib.pyplot as plt  ## Matplotlib.pyplot is the graphing library that we will be using throughout the semester
import random  ## Useful for sampling

import math  # Basic math library

import os  ## Useful for running command line within python
from IPython.display import Image  ## For markdown purposes

<div class="alert alert-block alert-info">

# Task 1 - Python basics <a class="anchor" id="python-basics"></a>
    
This Task will test your knowledge under five subsections. You will use the knowledge gained from the python tutorial to answer the question. 

- 1.1 Data types
- 1.2 Conditional statements
- 1.3 Loops 
- 1.4 Functions
- 1.5 Classes

<div class="alert alert-block alert-info">
    
## Learning Objective 
    
This task on Python basics aims to familiarize you with fundamental concepts and features of the Python programming language. By the end of this section, you should be able to understand and utilize data types, write conditional statements to make decisions in their code, implement loops for repetitive tasks, define and use functions for code reusability, and grasp the basics of object-oriented programming by creating and utilizing classes. This foundational knowledge will provide a solid understanding of Python's core concepts, enabling you to build more complex programs and tackle real-world programming challenges effectively.

<div class="alert alert-block alert-info">

## 1.1  Data types <a class="anchor" id="data-types"></a>

Python supports various data types such providing flexibility and versatility for data manipulation and analysis.

#### Before beginning, it is always good to know the basics of Python. Python have data types such as :

1. number
2. string
3. list
4. dictionary
5. tuple

#### (a) Create two lists named list_a and list_b with the values given in the Question 1 in the lab 1 quiz.

In [2]:
list_a = [24, 27, 30, 12, 15, 18, 21]  ##  list_a
list_b = [4, "1 2 3 7"]  ##  list_b

Do the following:
- Append list_b to the end of the list_a
- Extend new version of list_a with list_b.
- Print the length of final version of list_a.

You will find that the append method is useful in later labs as it allows you to append results at computation time.

In [4]:
list_a.append(list_b)  # type: ignore ## Append list_b to your list_a
list_a.extend(list_b)  ## then extend the result with list_b
print(f"Length of list is {len(list_a)}")
print(list_a)

Length of list is 13
[24, 27, 30, 12, 15, 18, 21, [4, '1 2 3 7'], 4, '1 2 3 7', [4, '1 2 3 7'], 4, '1 2 3 7']


#### (b) Create a dictionary with the following mappings.
- 'Unit' : 4179
- 'Session': 'Lab 1'
- 'Date': 'July 20, 2023'
- 'Pass' : 50,
- 'Students': ['Jim', 'Gary', 'Hon']
- 'Achieved' : [60, 40, 30]

'Achieved' and 'Students' are two keys in the dictionary that show the list of students and the score they achived in Lab 1.

Please do the following:
- Add your name to the value list of the 'Students'
- Append a score of 100 in the value 'Achieved' key.
- Add a new key to the dictionary named 'Required' which shows how many more scores each student need to earn in order to pass Lab 1.
- Obtain all the keys using .keys() method and print it out as a list.
- Obtain all the values using .values() method and print it out as a list.

Dictionaries are a good way to store information with a key that is easily accessible. This can become useful when you want to store learnt parameters of a model, and the hyper parameters used to train a model.

In [8]:
my_dict = {
    "Unit": 4179,
    "Session": "Lab 1",
    "Date": "July 20, 2023",
    "Pass": 50,
    "Students": ["Jim", "Gary", "Hon"],
    "Achieved": [60, 40, 30],
}

# Add your name to 'Students' key
my_dict["Students"].append("Lucas")

# Add your score of 100 to 'Achieved' key
my_dict["Achieved"].append(100)

# Add 'Required' key
# Add a new key to dictionary called 'Required' calculating how many points
# each students need to pass the lab
my_dict["Required"] = [max(0, 50 - f) for f in my_dict["Achieved"]]


print(my_dict.keys())
print(my_dict.values())

dict_keys(['Unit', 'Session', 'Date', 'Pass', 'Students', 'Achieved', 'Required'])
dict_values([4179, 'Lab 1', 'July 20, 2023', 50, ['Jim', 'Gary', 'Hon', 'Lucas'], [60, 40, 30, 100], [0, 10, 20, 0]])


<div class="alert alert-block alert-info">

## 1.2 Conditional statements <a class="anchor" id="conditional-statements"></a>

Conditional statements in Python allow for the execution of different code blocks based on specified conditions, enabling the creation of decision-making logic within a program. 
    
In Python, you need to use identation to specify the scope of conditional statements. It is highly recommended you use _tab_ for identation, rather than spaces, as it will format your code much nicer and become more readable. This would also give you less change to make mistakes.

#### (a) Code an IF statement to check how many elements from the prime_list divide the number

In [10]:
number = 10234  # number
prime_list1 = [2, 3, 5, 7, 11, 13, 17, 19, 23]  # prime_list

count = 0
for n in prime_list1:
    if number % n == 0:
        count += 1
print(count)

3


#### (b) Fill out the missing parts in the code to get “True” after each IF statement.
You may find the function _type_ to be useful. Remember, checking data types is useful in helping you debug for niche cases (such as applying operations on mismatching data types ). See here for documentation about _type_:

https://www.programiz.com/python-programming/methods/built-in/type

In [20]:
b_1 = "1 2"
b_2 = 2.3
b_3 = {1: 2}

print(
    (
        type(b_1) == "<class 'str'>"
        and type(b_2) == "<class 'float'>"
        and type(b_3) == "<class 'dict'>"
    )
)
# Check if all statements are True

False


#### (c)  Write an IF statement to check whether a year is a leap year.

Use '2' plus the last three digits of your student ID as the year.

For example, if your ID is 12563487, then the year to use is: 2487

__Note: If the year is divisible by 4 and not divisible by 100, or if it is divisible by 400, then it is a leap year__

In [21]:
year = 2579

if year % 4 == 0 and year % 100 != 0:

    print(f"The year {year} is a leap year")
elif year % 400 == 0:

    print(f"The year {year} is a leap year")
else:

    print(f"The year {year} is not a leap year")

The year 2579 is not a leap year


<div class="alert alert-block alert-info">

## 1.3 Loops <a class="anchor" id="loops"></a>

Python loops allow for the repetition of a block of code multiple times, making it efficient and convenient to perform iterative tasks or iterate over collections of data. Remember, indexing starts from 0! 
    
In Python, you need to use identation to specify the scope of loops. It is highly recommended you use _tab_ for identation, rather than spaces, as it will format your code much nicer and become more readable, and give you less chance to make indentation mistakes.

#### (a) Print out the numbers from n_1 to n_2 (inclusive) using a for loop.

You may find the _range_ function helpful. 

https://www.programiz.com/python-programming/methods/built-in/range

In [22]:
n_1 = 2  # Initialize n_1
n_2 = 13  # Initialize n_2
for num in range(n_1, n_2 + 1):  ## Print out the numbers from n_1 to n_2 (inclusive)
    print(num)

2
3
4
5
6
7
8
9
10
11
12
13


#### (b) For the numbers between b_1 and b_2 (not inclusive) given in the quiz question, print out how many numbers that are divisible by b_3.

Remember, you need identations for each loop and each conditional statement

In [23]:
b_1 = 32
b_2 = 690
b_3 = 7

count = 0
for i in range(b_1, b_2):
    if i % b_3:
        count += 1
print(count)

564


#### (c) For your student ID, keep dividing by 4 until it is a value lower than 10. Print out the final value.

_Hint: Use a while loop here_

In [24]:
student_number = 31445179

while student_number >= 10:
    student_number /= 4
print(student_number)

## Complete the task specified above

7.497114896774292


<div class="alert alert-block alert-info">

## 1.4 Functions <a class="anchor" id="functions"></a>
    
Python functions provide a way to encapsulate reusable blocks of code, allowing for modular and organized programming, and facilitating code reuse and readability. Always lay out the function with comments and useful variable names.

#### (a) Write a function that find the hypotenuse of a right triangle (Hint: use the Pythagorean theorem).

Please use the values provided in the quiz question.

In [25]:
def compute_hypotenuse(side_1, side_2):

    # Inputs:
    # side1 - the input argument for one side of the triangle
    # side2 - the input argument for another side of the triangle

    # Outputs:
    # hypotenuse - the calculated output from side1 and side2

    hypotenuse = (side_1 * side_2) ** 0.5

    return hypotenuse


side_1 = 9.31
side_2 = 42.67
out = compute_hypotenuse(side_1, side_2)
print(out)

19.93132459220912


#### (b) Write a function that computes the factorial of a given number. 
E.g. factorial_fn(5) → output: 120

Please use the last two digits of your student ID as inputs.

In [30]:
def factorial_fn(number):

    # Input argument(s):
    # number - the factorial we are trying to find

    # Output:
    # result - the factorial result of the number

    result = 1  # Initialize result to 1
    i = 1
    while i <= number:
        result *= i
        i += 1
    return result  # return result here


number = 79
print(factorial_fn(number))

894618213078297528685144171539831652069808216779571907213868063227837990693501860533361810841010176000000000000000000


<div class="alert alert-block alert-info">

## 1.5 Classes <a class="anchor" id="classes"></a>
    
Python classes are a fundamental component of object-oriented programming in Python, allowing developers to define blueprints for creating objects with their own attributes and behaviors.

##### Please complete the following:
1. Write a Python class **Student** with attributes student_id, student_name, and lab_day, lab1_marks.
2. In the same class, add method 'assign_lab_day' to change the allocated lab day of the student to given weekday.
3. In the same class, add method 'print_student_details' to print the details (related attributes) of a student.
4. In the same class, add method 'calculate_lab1_marks' that takes two arguments:
   1. No. of questions correctly answered
   1. Marks allocated per question
5. Computes the lab1 marks by using the below formula:

lab1 marks = (No. of questions correctly answered) $\times$ (Marks allocated per question)

In [ ]:
class Student:
    def __init__(self, ????, ????, ????, ????):
        # Save the object's attributes
        self.name = ????
        self.id = ????
        self.day = ????
        self.marks = ????
        
    def assign_lab_day(self, stud_lab_day):
        # Reassign the lab day
        ????
        
    def print_student_details(self):
        ## Method for printing all the student details, format it nicely
        print("----------------------")
        ????
        print("----------------------")
        
    def calculate_lab1_marks(self, num_questions, marks_per_ques):
        # Recalculation of lab 1 marks
        ????

##### Now create an instance of this class using following data.
- Name: your first name
- Student ID:  your student  ID
- Lab day:  allocated day of the week 
- Lab 1 marks: your expected score for this lab (out of 100)

Then print the details of the students using the ```print_student_details()``` method.


In [ ]:
student = Student(????, ????, ????, ????)
???? # Call the print method

Now do the following:
- Switch the lab day using ```assign_lab_day``` method to "Monday".
- The student had answered 3 questions correctly and each question carries 25 marks, ammend the lab1 marks of the student using the ```calculate_lab1_marks``` method.
- Reprint the students details.

In [ ]:
student.????  ## Reassign lab
student.????  ## Calculate marks based off what they achieved
student.???? 

<div class="alert alert-block alert-info">

# Task 2 - Data Analysis and Visualization <a class="anchor" id="data-analysis-and-visualization"></a>

Deep learning thrives on the synergy of data analysis and visualization, empowering us to unveil intricate patterns, extract meaningful features, and gain profound insights from complex datasets. This task will test your knowledge of two main python libraries that we often use for data analysis and visualization.

- 2.1 Numpy
- 2.2 Matplotlib

<div class="alert alert-block alert-info">
    
## Learning Objective 

This Data Analysis and Visualization section aims to provide you with the necessary skills to analyze and visualize data using two essential Python libraries: Numpy and Matplotlib. By the end of this task, you will be proficient in performing numerical computations with Numpy, processing datasets, and employing Matplotlib to create a variety of static and interactive visualizations. The acquired knowledge will empower you to uncover patterns, extract insights, and effectively communicate findings from complex datasets, confidently making informed decisions and addressing real-world data analysis challenges.

<div class="alert alert-block alert-info">

## 2.1 Numpy <a class="anchor" id="numpy"></a>

<img src="https://seeklogo.com/images/N/numpy-logo-479C24EC79-seeklogo.com.png" width="75" height="75" /> 
    
NumPy is a powerful Python library that stands for Numerical Python. It provides efficient numerical operations on large arrays and matrices of data, along with a vast collection of mathematical functions. With NumPy, users can perform array manipulation, mathematical computations, linear algebra operations, random number generation, and much more, making it a fundamental tool for scientific computing and data analysis in Python. In this task, we will be performing manipulations on numpy arrays and understanding how they interact with one another.

#### (a) Initialize python list, then convert it to a numpy array and print it out.

You may find the following numpy function useful:
- _array_

Numpy documentation can be found here: https://numpy.org/doc/

In [ ]:
my_list = ????  
x = np.????(my_list)[????] ## Select proper index range of the array
print(x)

#### (b) create and identity matrix, zero matrix, and a ones matrix of required size. Add them all together and print the final result.

You may find the following numpy functions useful:

- _eye_
- _zeros_
- _ones_

In [ ]:
identity = ???
zeros = ???
ones = ???

result = ????  ## Final result
print(result)

#### (c) Create a numpy array with values ranging from c_1 to c_2  then reshape it create following matrix.

You may find the following numpy functions useful:
- _arange_
- _reshape_

Now, you might be thinking what is the purpose of reshape? Later on in the semester, this will become a useful tool in being able to reshape our data so it fits the neural network. For example, when we pass in a 2D image, and want to perform some classification at the end, we need to be able to __reshape__ the tensor so it becomes 1-dimensional to get the class probabilities ! 

In [ ]:
c_1 = ????   
c_2 = ????
x = np.arange(????,????) ## Create the initial numpy array
y = x.reshape(????) ## Reshape the array
print(y)


#### (d) The marks of students are in the given list. Create the grade vector of the students
- If mark $>$ 50 → grade "A"
- If mark $\leq $ 50 → grade "B"

The function you'll use would be useful when you want to search for particular conditions within a numpy_array, perhaps using it as a threshold in classification

In [ ]:
marks_list = ???? 
marks = ???? ## Numpy array created from the list
status = ???? ## Using the numpy function to classify the grades
print(status)

#### (e) Create a 6x6 matrix and fill it with a checkerboard pattern.
Note that explicitly writing the elements of the matrix is not allowed, instead you need to use numpy functions in a smart way to create this matrix. Your output should look like below.      
Note: you may want to use a unique variable name to store this matrix since you will need to reuse it in Section 2.2(e).

[[0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0]]

In [ ]:
???? # Your code to generate the checkerboard pattern
print(checkerboard)

<div class="alert alert-block alert-success">

### (f) Reflection

#### Look at the following code examples and comment on what is happening in the following cases


In [ ]:
X = np.eye(2)
Y = np.array([[2, 5], [1, 3]])

print(f"\nX: \n{X}")
print(f"\nY: \n{Y}")

## case (i)
addXY = np.add(X, Y)
print(f"\ncase (a) \n{addXY}")
## case (ii)
addXY2 = X + Y
print(f"\ncase (b): \n{addXY2}")
## case (iii)
multXY = np.matmul(X, Y)
print(f"\ncase (c): \n{multXY}")
## case (iv)
multXY2 = X * Y
print(f"\ncase (d): \n{multXY2}")
## case (v)
powY = Y**2
print(f"\ncase (e): \n{powY}")
## case (vi)
powY2 = np.matmul(Y, Y)
print(f"\ncase (f): \n{powY2}")

<div class="alert alert-block alert-info">

## 2.2 Matplotlib <a class="anchor" id="matplotlib"></a>

<img src="https://seeklogo.com/images/M/matplotlib-logo-AEB3DC9BB4-seeklogo.com.png" height="50" />


Matplotlib is a popular Python library used for creating visualizations and plots. It provides a wide range of plotting functions and options, allowing users to create line plots, scatter plots, bar plots, histograms, and many other types of charts. Matplotlib provides a flexible and customizable interface, enabling users to fine-tune their plots with various styling options, labels, titles, and annotations. With its intuitive API and extensive documentation, Matplotlib is widely used in data exploration, scientific research, and data visualization tasks in Python.

#### (a) Let's plot a heart together
- Create a numpy array for t to be from 0 to $2\pi$ radian
- Define the x coordinates to be: $16 (sin(t))^3$
- Define the y coordinates to be: $13 cos(t) - 5 cos(2t) - 2 cos(3t) - cos(4t)$
- Use plt.plot for plotting, choose a colour for the plot line
- Create a title for the plot, and add your name and student ID to the title
- Make sure you add your x and y labels
- Limit the x and y axis range to -20 and 20
- You can play around with the colour and marker types

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Define the range of t
t = ?????

# Parametric equations for a heart shape
x = ?????
y = ?????

# Plot the heart shape
plt.figure(figsize=(8, 8))
plt.????   #plot the x and y values
plt.title('Heart Shape Curve')
plt.xlabel('x')
plt.ylabel('y')
plt.????? #limit the x axis
plt.????? #limit the y axis
plt.grid(True)
plt.axhline(0, color='black',linewidth=0.5)
plt.axvline(0, color='black',linewidth=0.5)
plt.gca().set_aspect('equal', adjustable='box')
plt.????? #show the plot

#### (b) Plot a noisy Parabola using a scatter plot by following the below instructions
- Create some empty lists to store x and y-axis values
- In a for-loop create the x and y values
- Compute x^2 and then add a random number from 0-1. The range of x values will be from [-2.5, 2.5]
- Plot y with respect to x 
- Find the minimum of the y values and find the corresponding x value. Then annotate that point as "minimum" using plt.annotate (Use different color for clarity)
- Make sure you add your x and y labels
- Create a title for the plot, and add your name and student ID to the title
- Play around with the colour and marker types

In [ ]:
import math
import random
x_parab_values = ????
y_parab_values = ????

for i in range(-50, 50): ## Using for loop
    x_parab_values.?????? ## Generate x values
    y_parab_values.?????? ## Generate the y-values based on the conditions specified

plt.scatter(x_parab_values, y_parab_values, c = "k", marker = "*") ## Add in plot, make sure you properly label it

a = ?????
b = ?????
plt.annotate("minimum", xy=????, color='r')

# Y-label, X-label, title
# In other cases, you may want to add in a legend, grid axis etc.
plt.ylabel('Y')
plt.xlabel('X')
plt.title("Noisy Parabola")
plt.show()

#### (c) Plot the audio waveform of a bird chirping using a line plot by following the below instructions
- Load the data in file "birdy.npy". It will load a numpy array of size (13129,2) in which the first column is the time indices and the second column is the amplitude values
- Use plt.plot for plotting
- x-axis should be the time index
- y-axis should be the Amplitude
- Make sure you add your x and y labels
- Create a title for the plot, and add your name and student ID to the title

In [ ]:
bird_chirp = np.????? ## load data
t, Amp = ???, ???? ## extract time indices and amplitude values

????? ## Add in plot, make sure you properly label it

# Y-label, X-label, title

plt.xlabel("time index")
plt.ylabel("Amplitude")
plt.title("Bird chirp waveform")
?????

#### (d) Plot a distribution using a bar plot by following the below instructions
- Use np.linspace to create 100 linearly spaced values for your x-axis from $\left[-d, +d\right]$
- Calculate the PDF values using the normal distribution formula with mean $\mu$ and variance $\sigma$
- Use plt.bar for plotting
- You may want to use the "width" parameter to make it more attractive
- Make sure you add your x and y labels
- Create a title for the plot, and add your name and student ID to the title.

For your convenience, the normal distribution is as follows:

$$ f(x) = \frac{1}{\sigma \sqrt{2\pi}} e^{-\frac{(x-\mu)^2}{2\sigma^2}}$$



In [ ]:
d = ????
mu = ????
sigma = ????


x = np.????? ## Use linspace to generate x-values
pdf =????? # Pass it through a normal distribution formula

plt.bar(????)

# Y-label, X-label, title
# In other cases, you may want to add in a legend, grid axis etc.

plt.xlabel('X')
plt.ylabel('Probability Density')
plt.title('PDF of Normal Distribution')
plt.show()

#### (e) Plot the contours of a paraboloid usng a contour plot by following the below instructions
- Use np.linspace to create 100 linearly spaced values for your x-axis from -1 to +1
- Use np.linspace to create 100 linearly spaced values for your y-axis from -2 to +2
- Use np.meshgrid to create a grid where the z-axis values can be evaluated
- Evaluate z-axis values using $z = x^2 + \frac{1}{4} y^2$
- Use plt.contourf for plotting
- Make sure the x- and y-axes are of equal scale
- Make sure to add a colorbar
- Make sure you add your x and y labels
- Create a title for the plot, and add your name and student ID to the title.

In [ ]:
x_vals = np.linspace(-1, 1, 100) ## Use linspace to generate x-values
y_vals = np.linspace(-2, 2, 100) ## Use linspace to generate y-values
X, Y = np.????? ## Use meshgrid to generate a grid

Z = ????? ## Evaluate z-values on the grid

plt.contourf(????) ## Add in the contour plot, make sure you properly label it
plt.axis('equal')
plt.colorbar()

# Y-label, X-label, title

plt.title('Contour Plot')
plt.xlabel('x')
plt.ylabel('y')
plt.show()

#### (f) Visualize a rotated checkerboard pattern using plt.imshow() by following the below instructions
- Use numpy array that you created in 2.1(d) and rotate it by 90 degrees
- Visualize it using plt.imshow()
- Make sure the image is black & white
- get rid of the x and y-axis ticks
- add a colorbar
- Create a title for the plot, and add your name and student ID to the title.

_plt.imshow_ is a way to display 2D arrays/tensors which will be useful in visualizing images or any results. We will be using this throughout the course.

_Hint: There is a rotation function within the numpy library that you could use_

In [ ]:
x_checkerboard_rot = ?????(x_checkerboard)
plt.imshow(?????) ## Use imshow to visualize the checkerboard made in 2.1e
plt.colorbar()
plt.title("Checkerboard")
plt.xticks([])
plt.yticks([])
plt.show()

#### Interesting fact:

Matplotlib provide its own script to generate the logo. You can [download the notebook or the python file here](https://matplotlib.org/stable/gallery/misc/logos2.html) to have a look.

<div class="alert alert-block alert-danger">

#### Congratulations on finishing the first part of lab 1. You can now do the second part of lab 1 where you will apply the things you have learnt so far to a geometric and mathematical problem.