In [1]:
import numpy as np

In [2]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


def relu(x):
    return np.where(x > 0, x, 0)

In [8]:
x = np.array([[-0.9, 0.4]]).T
w1 = np.array([[0.1, -0.8], [-0.4, -0.5], [0.1, 0.8]])
w2 = np.array([[0.1, -0.2, -0.4]])

l1 = relu(w1 @ x)
y_hat = sigmoid(w2 @ l1)
print(y_hat)

[[0.46903966]]


In [14]:
rates = np.array([[0.1, 10, 0.01, 1]])
w = np.array([[2.5]])


def q2_loss(w):
    return np.sin(w) + np.cos(3 * w)


def q2_grad(w):
    return np.cos(w) - 3 * np.sin(3 * w)


grad = q2_grad(w)
w_new = w - grad * rates
new_loss = q2_loss(w_new)
print(np.abs(new_loss).argmin())

1


In [14]:
dl_dyhat = np.array([[0, 7]]).T

x = np.array([[1, 2]]).T
w = np.array([[2, -5], [2, 3]])
z = w @ x
y_hat = relu(z)


dyhat_dz = np.where(y_hat > 0, 1, 0)

dz_dw = np.array([[x[0, 0], x[1, 0], 0, 0], [0, 0, x[0, 0], x[1, 0]]])

dl_dw = (dl_dyhat * dyhat_dz).T @ dz_dw
print(dl_dw)

[[ 0  0  7 14]]


In [34]:
w = np.array([[-0.5, -0.5]]).T


def forward(x):
    return x @ w


x = np.array([[-9.1, -2.7, 3.3, 8.4], [1, 1, 1, 1]]).T
y = np.array([[0.0, 2.3, 9.7, 15.6]]).T


def loss_fn(y, y_hat):
    return np.log(np.cosh(y_hat - y)).mean()


def loss_deriv(y, y_hat):
    return np.tanh(y_hat - y).mean()


y_hat = forward(x)
dl_dyhat = loss_deriv(y, y_hat)
dyhat_dw = x

dl_dw = (dl_dyhat * dyhat_dw).mean(0).reshape(-1, 1)
print(dl_dw)

w_new = w - 0.1 * dl_dw
print(w_new)

[[ 0.01185187]
 [-0.47407494]]
[[-0.50118519]
 [-0.45259251]]


In [35]:
import torch

In [41]:
logits = torch.tensor([3.7, 8.4, -1.5, 1.8, 1.5])
loss = torch.nn.NLLLoss()
softmax = torch.nn.Softmax()
s = softmax(logits)

print(s)
print(loss(logits, torch.tensor([0.0, 0.0, 0.0, 1.0, 0.0]).type(torch.long)))

tensor([8.9917e-03, 9.8862e-01, 4.9604e-05, 1.3449e-03, 9.9631e-04])
tensor(-3.7000)


In [45]:
x = np.array([[35, 29, 33, 30, 28], [1, 1, 1, 1, 1]]).T
y = np.array([[132, 112, 126, 115, 108]]).T

w = np.linalg.pinv(x) @ y
print(w)

print(w[0] * 34 + w[1])

[[ 3.44117647]
 [11.92352941]]
[128.92352941]


In [48]:
res = 28 * 28 + 1
layers = [64 + 1, 128 + 1, 256 + 1, 512 + 1]
out = 10

params = (
    res * layers[0]
    + layers[0] * layers[1]
    + layers[1] * layers[2]
    + layers[2] * layers[3]
    + layers[3] * out
)
print(params)

229534
